### ISSUE TITLE
getting unauthorized when trying to pull 'ghcr.io/whiteducksoftware/az-dns-forwarder/az-dns-forwarder:latest'

### ISSUE THREAD

**Issue by hectoralicea** [whiteducksoftware/az-dns-forwarder#1]
## Describe the bug
Failed to pull image "ghcr.io/whiteducksoftware/az-dns-forwarder/az-dns-forwarder:latest" Error response from daemon: Get https://ghcr.io/v2/whiteducksoftware/az-dns-forwarder/az-dns-forwarder/manifests/latest: unauthorized
 
## To Reproduce
```
kubectl apply -f https://raw.githubusercontent.com/whiteducksoftware/az-dns-forwarder/master/deploy.yaml
```

## Expected behavior
I would think the pods would start up.

## Screenshots/Logs
Following is the output for  `kc describe pods az-dns-forwarder-fc864c554-ctc82`
```
  Normal   Scheduled  47s                default-scheduler  Successfully assigned default/az-dns-forwarder-fc864c554-ctc82 to aks-pool01-30842998-vmss000001
  Normal   BackOff    19s (x3 over 45s)  kubelet            Back-off pulling image "ghcr.io/whiteducksoftware/az-dns-forwarder/az-dns-forwarder:latest"
  Warning  Failed     19s (x3 over 45s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    5s (x3 over 46s)   kubelet            Pulling image "ghcr.io/whiteducksoftware/az-dns-forwarder/az-dns-forwarder:latest"
  Warning  Failed     5s (x3 over 46s)   kubelet            Failed to pull image "ghcr.io/whiteducksoftware/az-dns-forwarder/az-dns-forwarder:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://ghcr.io/v2/whiteducksoftware/az-dns-forwarder/az-dns-forwarder/manifests/latest: unauthorized
  Warning  Failed     5s (x3 over 46s)   kubelet            Error: ErrImagePull
```

## Additional context
I need this to then be able to access the azurecr  so I cant put your image in my own repo, since we are doing a boot strap with no containers available to place your image.  I would be nice if it existed in dockerhub for anonymous pull.

**Comment by nmeisenzahl** [comment]
Hi @hectoralicea!

GitHub Packages (used to store the image) are not allowing anonymous access. You will have to authenticate with your GitHub credentials or PAT. 

There are multiple options to achieve this. One is to configure an imagePullSecret for the used service account. More details are available [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account). Another option would be to build and pull your own image. The required Dockerfile is part of this repo.

I might migrate this project to the GitHub Container Registry in the future. This will then also allow unauthorized access.

Greets Nico
