### ISSUE TITLE
The image 'ghcr.io/whiteducksoftware/az-dns-forwarder/az-dns-forwarder:latest' in container group 'dns-forwarder' is not accessible.

### ISSUE THREAD

**Issue by duvaneck** [whiteducksoftware/az-dns-forwarder#2]
## Describe the bug
The image 'ghcr.io/whiteducksoftware/az-dns-forwarder/az-dns-forwarder:latest' in container group 'dns-forwarder' is not accessible. Please check the image and registry credential.

**Comment by nmeisenzahl** [comment]
Hi @duvaneck you will have to authenticate to access the container image. You will find more details in [this](https://github.com/whiteducksoftware/az-dns-forwarder/issues/1#issuecomment-748349036) issue.
